/**
 * Generated by tsnapi — public API snapshot of `@mcbe-mods/utils`
 */
// #region Interfaces
export interface Location {
  x: number;
  y: number;
  z: number;
}
// #endregion

// #region Types
export type Stylizer = {
  (..._: string[]): string;
} & { [P in StyleId]: Stylizer };
// #endregion

// #region Classes
export declare class Experience {
  #private;
  getTotalXP(): number;
  getNextLevelRequiredXP(): number;
  addXP(_: number): this;
  getXP(): number;
  setXP(_: number): this;
  addLevel(_: number): this;
  getLevel(): number;
  setLevel(_: number): this;
}
// #endregion

// #region Functions
export declare function calcGameTicks(_?: number, _?: number, _?: number): number;
export declare function getRadiusRange(_: Location, _?: number): Location[];
export declare function getRandomProbability(_: number): boolean;
export declare function getRandomRangeValue(_: number, _: number): number;
export declare function splitGroups(_: number, _?: number): number[];
// #endregion

// #region Variables
export declare const color: Stylizer;
// #endregion